services:
  api:
    restart: always
    build: ./server/
    container_name: proxyfinder-api
    command: bash -c " cd /app && make up-api"
    volumes:
      - ./server/config:/app/config
      - ./server/storage:/app/storage
      - ./server/build:/app/build
      - ./server/Makefile:/app/Makefile
      - ./logs/api:/app/logs
    ports:
      - 8080:8080
    depends_on:
      migrate:
        condition: service_completed_successfully

  scheduler:
    build: ./server/
    container_name: proxyfinder-scheduler
    command: bash -c " cd /app && make up-scheduler"
    volumes:
      - ./server/config:/app/config
      - ./server/storage:/app/storage
      - ./server/build:/app/build
      - ./server/Makefile:/app/Makefile
      - ./logs/scheduler:/app/logs
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    build: ./server/
    container_name: proxyfinder-migrate
    command: bash -c "cd /app && make migrate"
    volumes:
      - ./server/storage:/app/storage
      - ./server/build:/app/build
      - ./server/migrations:/app/migrations/
      - ./server/config:/app/config
      - ./server/Makefile:/app/Makefile

  frontend:
    image: nginx:1.26-alpine
    container_name: proxyfinder-frontend
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./frontend/dist:/app/frontend/dist
      - ./admin/dist:/app/admin/dist
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/frontend:/var/log/nginx
    restart: always
    depends_on:
      - api
