services:
  api:
    build: ./server/
    container_name: proxyfinder-api
    command: bash -c " 
      cd /app && \
      build/api --config /app/config/prod.yaml"
    volumes:
      - ./server/config:/app/config
      - ./server/storage:/app/storage
      - ./server/build:/app/build
    env_file: ./.env
    ports:
      - 8080:8080
    depends_on:
      - migrate

  scheduler:
    build: ./server/
    container_name: proxyfinder-scheduler
    command: bash -c " 
      cd /app && \
      build/scheduler --config /app/config/prod.yaml"
    volumes:
      - ./server/config:/app/config
      - ./server/storage:/app/storage
      - ./server/build:/app/build
    env_file: ./.env
    depends_on:
      - migrate
  
  migrate:
    build: ./server/
    container_name: proxyfinder-migrate
    command: bash -c "
      cd /app && \
      build/goose -dir migrations/goose sqlite3 ./storage/prod.db up && \
      build/initdb --config config/prod.yaml up"
    volumes:
      - ./server/storage:/app/storage
      - ./server/build:/app/build
      - ./server/migrations:/app/migrations/
      - ./server/config:/app/config
    env_file: ./.env

  frontend:
    image: nginx:1.26-alpine
    container_name: proxyfinder-frontend
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend/dist:/app/frontend/dist
      - ./admin/dist:/app/admin/dist
      - ./nginx.conf:/etc/nginx/nginx.conf
